### ISSUE TITLE
Any way to run task asynchrounously

### ISSUE THREAD

**Issue by msmolka** [justdmitry/RecurrentTasks#1]
I'm using third party libraries that have only asynchronous methods. So it is possible to make method Run asynchronous.?

**Comment by justdmitry** [comment]
All tasks are living in separate/own `Task` objects, which sleeps between executions. Having `RunAsync` will not add any optimization to application - this `Task` will sleep little more, but it still a `Task`. (Or will?)

Currently, instead of building complex cast/try/catch solution for supporting both `IRunnable` and (possible) `IRunnableAsync` I use this kind of implementation:

    public void Run(ITask currentTask)
    {
        RunAsync(currentTask).Wait();
    }

    public async Task RunAsync(ITask currentTask)
    {
        ...
    }

If you have idea(s) about easy adding `IRunnableAsync` (or something like it) - your PR are welcome.

**Comment by msmolka** [comment]
Thanks, I will try use that

**Comment by LordMike** [comment]
Note that simply calling "Wait" will make it impossible to achieve any benefits from the TPL framework in Dotnet (asynchronous I/O for one). RecurrentTasks should at its core be async all the way.

I know that right now it'll still end up in a Synchronous method somewhere in RecurrentTasks, but at least this way, once it's figured out how to make it truly async - it will benefit all current IRunnable(s). As it is now, once RecurrentTasks becomes async, code that uses it will have to be rewritten to make use of async.

**Comment by justdmitry** [comment]
@LordMike I guess you're writing about running some separate/different tasks in parallel (with TPL)? Otherwise, inside single IRunnable.Run, having Wait() on top of async "tree" will not hurt any "deep" async calls (AFAIK).

I agree that we all now live in async world and "modern" is almost always "async" (not "sync"), but this library helps me run some "independent" tasks (refresh memory cache of "static" data once in hour, cleanup old users several times per day) and not intended for cross-task synchronization. Can you share your app/task details - why you need cross-task parallel/synchronized execution?

**Comment by LordMike** [comment]
Purely a comment. Yes, most tasks will be of a sorts that won't require anything extra, such as short tasks.

The tasks that would benefit from a completely `async` call tree, are those that do a form of IO, such as network or disk. In those cases, .NET will be able to sideline the running `Task` while waiting for the completion of said IO, giving CPU time to other `Task`s. Implementing a `Wait()`, as I remember it, will synchronously block a thread while waiting for others.

So Tasks that f.ex. do some database work, copy / read / write files around and such, will be able to benefit from `async`. The rest probably won't :).

**Comment by justdmitry** [comment]
`void Run` changed to `Task RunAsync` in [v5](https://github.com/justdmitry/RecurrentTasks/releases/tag/v5.0.0), but that's only a facelift - internally one "supervisor" Task still exists. His duty is to sleep between runs and wait for single run to complete. Have no idea how to escape this.
