### ISSUE TITLE
Stopping the task by a cancellation token

### ISSUE THREAD

**Issue by poulad** [justdmitry/RecurrentTasks#3]
Is there a way to send a cancellation token to the task to stop it?

for example:

```c#
app.StartTask<SampleTask>(TimeSpan.FromSeconds(15), TimeSpan.FromSeconds(5), source.Token);
```

**Comment by justdmitry** [comment]
Currently - no. 

As a fast workaround, you may try to use [token.Register](https://docs.microsoft.com/en-us/dotnet/api/system.threading.cancellationtoken.register) with `Action` that stops task.

In all my use cases I start/stop tasks (a) never (b) only from administration page (during some maintenance). 

What is your use case from stopping Task (stopping "forever", because cancellation token is not "undoable") with cancellation token?

**Comment by poulad** [comment]
@justdmitry My use case is cancelling the task for ever only after some async method(`DoSomething()`) finishes its job. I'd like to pass the cancellation token from `DoSomething` method to the task (`SampleTask`) runner. Then, `DoSomething` decides on when to stop the task (for ever).

**Comment by justdmitry** [comment]
Implemented [in v5](https://github.com/justdmitry/RecurrentTasks/releases/tag/v5.0.0)
